### ISSUE TITLE
Update python-raet for Redhat 6 & 7 Salt 2016.3.5 and 2016.11.0

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#184]
see https://github.com/saltstack/salt/issues/25858#issuecomment-265498681

[x] 2016.3.5
[x] 2016.11.1

**Comment by dmurphy18** [comment]
Done for 2016.11.1 build infrastructure, waiting for tag

**Comment by dmurphy18** [comment]
Done for 2016.3.5 build infrastructure, waiting for tag

**Comment by dmurphy18** [comment]
closing this since infrastructure is updated and it will be available with 2016.3.5, 2016.11.1 is already released

**Comment by stonegithup** [comment]
[DEBUG   ] LazyLoaded config.merge
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 129, in minion_process
    minion.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 345, in start
    self.minion.tune_in()
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/__init__.py", line 146, in tune_in
    consolepath=consolepath,
  File "/usr/lib/python2.6/site-packages/ioflo/app/run.py", line 137, in run
    skedder.run()
  File "/usr/lib/python2.6/site-packages/ioflo/base/skedding.py", line 273, in run
    status = tasker.runner.send(tasker.desire)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 630, in makeRunner
    self.enterAll() #activates, resets .done state also .desire may change here
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 411, in enterAll
    self.enter(self.actives)
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 423, in enter
    frame.enter()
  File "/usr/lib/python2.6/site-packages/ioflo/base/framing.py", line 1244, in enter
    act() #call entryAction
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 99, in __call__
    return (self.actor(**self.parms))
  File "/usr/lib/python2.6/site-packages/ioflo/base/acting.py", line 524, in __call__
    return self.action(**kwa)
  File "/usr/lib/python2.6/site-packages/salt/daemons/flo/core.py", line 292, in action
    stackname=name)
  File "/usr/lib/python2.6/site-packages/salt/daemons/salting.py", line 62, in __init__
    self.saltRaetKey = RaetKey(opts)
  File "/usr/lib/python2.6/site-packages/salt/key.py", line 940, in __init__
    Key.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/key.py", line 372, in __init__
    listen=False)
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 145, in get_event
    opts=opts)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 50, in __init__
    self.__prep_stack(listen)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 60, in __prep_stack
    self.stack = transport.jobber_stack = self._setup_stack(ryn=self.ryn)
  File "/usr/lib/python2.6/site-packages/salt/utils/raetevent.py", line 98, in _setup_stack
    name = 'event' + nacling.uuid(size=18)
  File "/usr/lib/python2.6/site-packages/raet/nacling.py", line 576, in uuid
    return ((front + back)[:size]).decode(encoding='ISO-8859-1')
TypeError: decode() takes no keyword arguments

salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: 0.6.6
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.6 Final
        machine: x86_64
        release: 2.6.32-504.30.3.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final

I'm install  latest version .but still an issue in CentOS 6.6 .

**Comment by dmurphy18** [comment]
The changes in saltstack/raet#70 are not reflected in the latest version of raet v0.6.6. To resolve this issue, need to patch raet on Redhat 6 & 5 where python 2.6 is in use.

**Comment by dmurphy18** [comment]
Patched written, waiting for next release

**Comment by dmurphy18** [comment]
Now fixed in 2016.11.2 and 2016.3.5 for Redhat 6
