### ISSUE TITLE
Update Salt 2016.11.5 support for pycrypto flavors on Redhat family

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#261]
Updating python-impacket to have a requirement for python-crypto. Debian / Ubuntu and GitHub state this dependency but the Redhat family do not have it so.  Hence an updated version of python-impacket from Redhat family repos will not have this requirement and the user will have to install python-crypto manually.
Solution for https://github.com/saltstack/salt/issues/40900

Also patch pycryptodome to handle MD5 issues on a Redhat FIPS installed environment
Solution for https://github.com/saltstack/salt/issues/40890

**Comment by dmurphy18** [comment]
This moving to Salt 2016.11.5 which will contains two hot-fixes.
Expect to tag Monday

**Comment by dmurphy18** [comment]
https://github.com/saltstack/salt/issues/40890

**Comment by dmurphy18** [comment]
The patch for pycryptodomex is not working and in addition
root@localhost:~# /usr/bin/salt-master -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
[ERROR   ] local variable 'sig' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 201, in parse_args
    process_option_func()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 521, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 1715, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3310, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3329, in apply_master_config
    import salt.crypt
  File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 27, in <module>
    from Cryptodome.Cipher import AES, PKCS1_OAEP
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Cipher/__init__.py", line 78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
    from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/lib64/python2.7/site-packages/Cryptodome/Util/_raw_api.py", line 89, in <module>
    Array = ffi.new("uint8_t[1]").__class__.__bases__
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 248, in new
    cdecl = self._typeof(cdecl)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 168, in _typeof
    result = self._typeof_locked(cdecl)
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 153, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 448, in parse_type
    return self.parse_type_and_quals(cdecl)[0]
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 451, in parse_type_and_quals
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 260, in _parse
    ast = _get_parser().parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 40, in _get_parser
    _parser_cache = pycparser.CParser()
  File "/usr/lib/python2.7/site-packages/pycparser/c_parser.py", line 111, in __init__
    outputdir=taboutputdir)
  File "/usr/lib/python2.7/site-packages/ply/yacc.py", line 3065, in yacc
    signature = pinfo.signature()
  File "/usr/lib/python2.7/site-packages/ply/yacc.py", line 2814, in signature
    return sig.digest()
UnboundLocalError: local variable 'sig' referenced before assignment
2795     # Compute a signature over the grammar
2796     def signature(self):
2797         try:
**2798             from hashlib import md5
2799         except ImportError:
2800             from md5 import md5**
2801         try:
2802             sig = md5()
2803             if self.start:
2804                 sig.update(self.start.encode('latin-1'))
2805             if self.prec:
2806                 sig.update("".join(["".join(p) for p in self.prec]).encode('latin-1'))
2807             if self.tokens:
2808                 sig.update(" ".join(self.tokens).encode('latin-1'))
2809             for f in self.pfuncs:
2810                 if f[3]:
2811                     sig.update(f[3].encode('latin-1'))
2812         except (TypeError,ValueError):
2813             pass
2814         return sig.digest()

The problem is not limited to pycryptodomex since the code from yacc.py also similarly uses hashlib and md5 similar to pycryptodomex.

**Comment by dmurphy18** [comment]
root@localhost:~# find /usr/lib/python2.7 -name "*.py" | xargs grep "hashlib import md5"
/usr/lib/python2.7/site-packages/ply/yacc.py:            from hashlib import md5
/usr/lib/python2.7/site-packages/setuptools/command/upload.py:    from hashlib import md5
grep: /usr/lib/python2.7/site-packages/setuptools/script: No such file or directory
grep: template: No such file or directory
grep: (dev).py: No such file or directory
grep: /usr/lib/python2.7/site-packages/setuptools/script: No such file or directory
grep: template.py: No such file or directory
/usr/lib/python2.7/site-packages/ipapython/ssh.py:from hashlib import md5, sha1
/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py:from hashlib import md5, sha1, sha256
root@localhost:~# find /usr/lib64/python2.7 -name "*.py" | xargs grep "hashlib import md5"
/usr/lib64/python2.7/distutils/command/upload.py:from hashlib import md5
/usr/lib64/python2.7/md5.py:from hashlib import md5
/usr/lib64/python2.7/site-packages/tornado/test/curl_httpclient_test.py:from hashlib import md5
/usr/lib64/python2.7/site-packages/Cryptodome/Hash/MD5.py:        from hashlib import md5 as _hash_new
/usr/lib64/python2.7/uuid.py:    from hashlib import md5
root@localhost:~#

**Comment by dmurphy18** [comment]
The same issues are occurring with salt-minion.
It would appear that pycryptodomex cannot be used in a FIPS environment.
Logging upstream issue against pycryptodomex

For now FIPS environments on 64-bit Redhat 6 & 7 should do the following:
rpm -e --nodeps python2-pycryptodomex
yum install python-crypto
restart salt-master and salt-minion
