### ISSUE TITLE
Salt repo for Centos 6 needs pygit2 or gitpython added to it

### ISSUE THREAD

**Issue by josemine** [saltstack/salt-pack#375]
The latest version of the salt repo on Centos uses it's own version of python27, so  installing pygit2 or gitpython installs for python26. The salt repo needs to have one of these python modules added to it.
What led me to this issue was syncing winrepo
```
# salt-run winrepo.update_git_repos
[INFO    ] Executing command ['git', '--version'] in directory '/srv/salt'
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrepo.git
Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 392, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/winrepo.py", line 207, in update_git_repos
    force_reset=True)
  File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 701, in latest
    saltenv=__env__)
NameError: global name '__env__' is not defined
```

**Comment by racooper** [comment]
Definitely needs to get this resolved somehow.  I can't upgrade to 2018.03 without GitPython or pygit2 for Python 2.7, and the workarounds with pip2.7 I've found are not working.

**Comment by dmurphy18** [comment]
@josemine Going to look into porting gitPython to Python 2.7 for Redhat 6, and if no issues, it should be available by the next point release

**Comment by dmurphy18** [comment]
@josemine Have ported libgit2 and pygit2 to Redhat 6 using Python 2.7 and should be available with the next point release which is not too long off.
