### ISSUE TITLE
On Ubuntu 16.04 something is affecting dsc files causing re-runs to fail

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack#455]
During automation development getting errors re-running repo generation

root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
ERROR: '/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc' cannot be included as 'pool/main/libs/libsodium/libsodium_1.0.8-5.dsc'.
Already existing files can only be included again, if they are the same, but:
md5 expected: c815ea7e75e7c3181d6b7ccbffd5c82b, got: b7e222b400e13404cad3887e13cda8e8
sha1 expected: c6ce44b32e09990bf221ba83d941ec456b6fa065, got: ded5e3b7a9a498c600ea8294fa297d9356eb2101
sha256 expected: 59ecde822607060e98ca6984ecca447e9fc85667082f055df989db1a5bd94acb, got: 94f0296cd291b32a29f5544ca4eb6fce7279b9328de9b2b87dc3d766eeec563c
There have been errors!
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# rm -fR conf/ pool/ dists/ db/
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
Error opening config file './conf/distributions': No such file or directory(2)
There have been errors!
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# rm -fR conf/ pool/ dists/ db/
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
Skipping inclusion of 'libsodium' '1.0.8-5' in 'xenial|main|source', as it has already '1.0.8-5'.
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
Skipping inclusion of 'libsodium' '1.0.8-5' in 'xenial|main|source', as it has already '1.0.8-5'.
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# md5sum /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc2d95e29a77e281175b64b9f5a0a90270  /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# ls -al /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
-rw-r--r-- 1 root root 1674 Nov 15 23:00 /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# md5sum /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
43f9983a9255a842439bbf2ca4e4021d  /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# ls -al /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
-rw-r--r-- 1 root root 1674 Nov 15 23:02 /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
root@svc-builder-autotest-u16m:/srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64# 

due to re-run of 
salt svc-builder-autotest-u16m state.sls repo.ubuntu.ubuntu16  pillar='{ "build_dest" : "/srv/ubuntu/2017_7nb201711151153325671490/pkgs", "keyid" : "4DD70950" , "build_version" : "2017_7" }'
svc-builder-autotest-u16m:
----------
          ID: ensure_user_access
    Function: file.directory
        Name: /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64
      Result: True
     Comment: Directory /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64 is in the correct state
              Directory /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64 updated
     Started: 23:02:03.229286
    Duration: 131.094 ms
     Changes:   
----------
          ID: /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64
    Function: pkgbuild.repo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 372, in repo
                  res = __salt__[func](name, keyid, env, use_passphrase, gnupghome, runas, timeout)
                File "/usr/lib/python2.7/dist-packages/salt/modules/debbuild.py", line 775, in make_repo
                  'Reprepro includedsc for codename {0} and file {1} failed with proc.status {2}'.format(codename, abs_file, proc_exitstatus)
              SaltInvocationError: Reprepro includedsc for codename xenial and file /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc failed with proc.status 254
     Started: 23:02:03.361946
    Duration: 6593.671 ms
     Changes:   

Summary for svc-builder-autotest-u16m
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time:   6.725 s
ERROR: Minions returned with non-zero exit code
root@c7master:/srv/salt/auto_setup/orch# 

The file time date size unchanged but the md5sum (and others like sha1sum) are changing but there is nothing in the log (trace) showing the file being touched

**Comment by dmurphy18** [comment]
removing conf, db,dists and pool and re-running the script shows no errors and can run  
reprepro --ignore=wrongdistribution --component=main -Vb . includedsc xenial /srv/ubuntu/2017_7nb201711151153325671490/pkgs/ubuntu1604/amd64/libsodium_1.0.8-5.dsc
Skipping inclusion of 'libsodium' '1.0.8-5' in 'xenial|main|source', as it has already '1.0.8-5'.

shows no errors.
